# Generated by SQL Server Management Studio at 10:00 on 9/6/2023

Import-Module SqlServer -MinimumVersion 22.0.59
# Set up connection and database SMO objects

$password = "<replace with your password>"
$sqlConnectionString = "Data Source=localhost;Initial Catalog=EncryptedColumnsDb;User ID=sa;Password=$password;Multiple Active Result Sets=False;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name=`"Microsoft SQL Server Management Studio`""
$smoDatabase = Get-SqlDatabase -ConnectionString $sqlConnectionString

# If your encryption changes involve keys in Azure Key Vault/Managed HSM, uncomment the lines under one of the below options in order to authenticate:

# Option 1  * Prompt for a username and password:
#Connect-AzAccount

# Option 2  * Connect to Azure account using Client ID and Secret:
#$SecureSecret = ConvertTo-SecureString -String '<Secret>' -AsPlainText -Force
#$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList '<Client ID>', $SecureSecret
#Connect-AzAccount -ServicePrincipal -Credential $Credential -Tenant '<Tenant ID>'

# Uncomment below line to set subscription id in which you've key vault/Managed HSM.
#Set-AzContext -Subscription '<Subscription ID>'

# Uncomment below line to fetch key vault access token if you're using Azure Key Vault keys.
#$keyVaultAccessToken = (Get-AzAccessToken -ResourceUrl https://vault.azure.net).Token

# Uncomment below line to fetch Managed HSM access token if you're using Managed HSM keys.
#$managedHSMAccessToken = (Get-AzAccessToken -ResourceUrl https://managedhsm.azure.net).Token

# Change encryption schema

$encryptionChanges = @()

# Add changes for table [dbo].[User]
$encryptionChanges += New-SqlColumnEncryptionSettings -ColumnName dbo.User.SocialSecurityNumber -EncryptionType Deterministic -EncryptionKey "CEK_Auto1"


# Uncomment ONLY ONE of the below 4 options based on the conditions specified in the comment.

# Option 1: If your encryption changes do not involve keys in Azure Key Vault and Managed HSM, uncomment the below line.
#Set-SqlColumnEncryption -ColumnEncryptionSettings $encryptionChanges -InputObject $smoDatabase

# Option 2: If your encryption changes involve keys in both Azure Key Vault and Managed HSM, uncomment the below line.
#Set-SqlColumnEncryption -ColumnEncryptionSettings $encryptionChanges -InputObject $smoDatabase -KeyVaultAccessToken $keyVaultAccessToken -ManagedHSMAccessToken $managedHSMAccessToken

# Option 3: If your encryption changes involve keys in Azure Key Vault, uncomment the below line.
#Set-SqlColumnEncryption -ColumnEncryptionSettings $encryptionChanges -InputObject $smoDatabase -KeyVaultAccessToken $keyVaultAccessToken

# Option 4: If your encryption changes involve keys in Managed HSM, uncomment the below line.
#Set-SqlColumnEncryption -ColumnEncryptionSettings $encryptionChanges -InputObject $smoDatabase -ManagedHSMAccessToken $managedHSMAccessToken

